<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_SearchActor_Response</code>
 */
class M2B_SearchActor_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 actor_id = 1;</code>
     */
    private $actor_id = 0;
    /**
     * <code>string actor_name = 2;</code>
     */
    private $actor_name = '';
    /**
     * <code>string wx_union_id = 3;</code>
     */
    private $wx_union_id = '';
    /**
     * <code>string wx_open_id = 4;</code>
     */
    private $wx_open_id = '';
    /**
     * <code>string card_count = 5;</code>
     */
    private $card_count = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>string actor_name = 2;</code>
     */
    public function getActorName()
    {
        return $this->actor_name;
    }

    /**
     * <code>string actor_name = 2;</code>
     */
    public function setActorName($var)
    {
        GPBUtil::checkString($var, True);
        $this->actor_name = $var;
    }

    /**
     * <code>string wx_union_id = 3;</code>
     */
    public function getWxUnionId()
    {
        return $this->wx_union_id;
    }

    /**
     * <code>string wx_union_id = 3;</code>
     */
    public function setWxUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wx_union_id = $var;
    }

    /**
     * <code>string wx_open_id = 4;</code>
     */
    public function getWxOpenId()
    {
        return $this->wx_open_id;
    }

    /**
     * <code>string wx_open_id = 4;</code>
     */
    public function setWxOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wx_open_id = $var;
    }

    /**
     * <code>string card_count = 5;</code>
     */
    public function getCardCount()
    {
        return $this->card_count;
    }

    /**
     * <code>string card_count = 5;</code>
     */
    public function setCardCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_count = $var;
    }

}

