<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetTodayRechargeCardCount_Response</code>
 */
class M2B_GetTodayRechargeCardCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.TodayRechargeCardCount todayRechargeCardCount = 1;</code>
     */
    private $todayRechargeCardCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.TodayRechargeCardCount todayRechargeCardCount = 1;</code>
     */
    public function getTodayRechargeCardCount()
    {
        return $this->todayRechargeCardCount;
    }

    /**
     * <code>repeated .manager.TodayRechargeCardCount todayRechargeCardCount = 1;</code>
     */
    public function setTodayRechargeCardCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\TodayRechargeCardCount::class);
        $this->todayRechargeCardCount = $arr;
    }

}

