<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.Recharge</code>
 */
class Recharge extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 rank = 1;</code>
     */
    private $rank = 0;
    /**
     * <code>int32 actor_id = 2;</code>
     */
    private $actor_id = 0;
    /**
     * <code>int32 card_count = 3;</code>
     */
    private $card_count = 0;
    /**
     * <code>int32 money = 4;</code>
     */
    private $money = 0;
    /**
     * <code>string nick_name = 5;</code>
     */
    private $nick_name = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 rank = 1;</code>
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * <code>int32 rank = 1;</code>
     */
    public function setRank($var)
    {
        GPBUtil::checkInt32($var);
        $this->rank = $var;
    }

    /**
     * <code>int32 actor_id = 2;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 2;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>int32 card_count = 3;</code>
     */
    public function getCardCount()
    {
        return $this->card_count;
    }

    /**
     * <code>int32 card_count = 3;</code>
     */
    public function setCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_count = $var;
    }

    /**
     * <code>int32 money = 4;</code>
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * <code>int32 money = 4;</code>
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->money = $var;
    }

    /**
     * <code>string nick_name = 5;</code>
     */
    public function getNickName()
    {
        return $this->nick_name;
    }

    /**
     * <code>string nick_name = 5;</code>
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nick_name = $var;
    }

}

