<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

namespace Head;

/**
 * Protobuf enum <code>head.Cmd</code>
 */
class Cmd
{
    /**
     * <code>CMD_NoUse = 0;</code>
     */
    const CMD_NoUse = 0;
    /**
     * <code>CMD_Heartbeat_Request = 1001;</code>
     */
    const CMD_Heartbeat_Request = 1001;
    /**
     * <code>CMD_Heartbeat_Response = 1002;</code>
     */
    const CMD_Heartbeat_Response = 1002;
    /**
     * <code>CMD_Error_Response = 1003;</code>
     */
    const CMD_Error_Response = 1003;
}

