<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.RecentCreateRoom</code>
 */
class RecentCreateRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>int64 create_time = 2;</code>
     */
    private $create_time = 0;
    /**
     * <code>int32 room_id = 3;</code>
     */
    private $room_id = 0;
    /**
     * <code>int32 times_type = 4;</code>
     */
    private $times_type = 0;
    /**
     * <code>int32 played_times = 5;</code>
     */
    private $played_times = 0;
    /**
     * <code>int32 player1_actor_id = 6;</code>
     */
    private $player1_actor_id = 0;
    /**
     * <code>int32 player2_actor_id = 7;</code>
     */
    private $player2_actor_id = 0;
    /**
     * <code>int32 player3_actor_id = 8;</code>
     */
    private $player3_actor_id = 0;
    /**
     * <code>int32 player4_actor_id = 9;</code>
     */
    private $player4_actor_id = 0;
    /**
     * <code>int32 player1_scores = 10;</code>
     */
    private $player1_scores = 0;
    /**
     * <code>int32 player2_scores = 11;</code>
     */
    private $player2_scores = 0;
    /**
     * <code>int32 player3_scores = 12;</code>
     */
    private $player3_scores = 0;
    /**
     * <code>int32 player4_scores = 13;</code>
     */
    private $player4_scores = 0;
    /**
     * <code>int32 consume_card_count = 14;</code>
     */
    private $consume_card_count = 0;
    /**
     * <code>string player1_wx_name = 15;</code>
     */
    private $player1_wx_name = '';
    /**
     * <code>string player2_wx_name = 16;</code>
     */
    private $player2_wx_name = '';
    /**
     * <code>string player3_wx_name = 17;</code>
     */
    private $player3_wx_name = '';
    /**
     * <code>string player4_wx_name = 18;</code>
     */
    private $player4_wx_name = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;
    }

    /**
     * <code>int64 create_time = 2;</code>
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * <code>int64 create_time = 2;</code>
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;
    }

    /**
     * <code>int32 room_id = 3;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <code>int32 room_id = 3;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkInt32($var);
        $this->room_id = $var;
    }

    /**
     * <code>int32 times_type = 4;</code>
     */
    public function getTimesType()
    {
        return $this->times_type;
    }

    /**
     * <code>int32 times_type = 4;</code>
     */
    public function setTimesType($var)
    {
        GPBUtil::checkInt32($var);
        $this->times_type = $var;
    }

    /**
     * <code>int32 played_times = 5;</code>
     */
    public function getPlayedTimes()
    {
        return $this->played_times;
    }

    /**
     * <code>int32 played_times = 5;</code>
     */
    public function setPlayedTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->played_times = $var;
    }

    /**
     * <code>int32 player1_actor_id = 6;</code>
     */
    public function getPlayer1ActorId()
    {
        return $this->player1_actor_id;
    }

    /**
     * <code>int32 player1_actor_id = 6;</code>
     */
    public function setPlayer1ActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->player1_actor_id = $var;
    }

    /**
     * <code>int32 player2_actor_id = 7;</code>
     */
    public function getPlayer2ActorId()
    {
        return $this->player2_actor_id;
    }

    /**
     * <code>int32 player2_actor_id = 7;</code>
     */
    public function setPlayer2ActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->player2_actor_id = $var;
    }

    /**
     * <code>int32 player3_actor_id = 8;</code>
     */
    public function getPlayer3ActorId()
    {
        return $this->player3_actor_id;
    }

    /**
     * <code>int32 player3_actor_id = 8;</code>
     */
    public function setPlayer3ActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->player3_actor_id = $var;
    }

    /**
     * <code>int32 player4_actor_id = 9;</code>
     */
    public function getPlayer4ActorId()
    {
        return $this->player4_actor_id;
    }

    /**
     * <code>int32 player4_actor_id = 9;</code>
     */
    public function setPlayer4ActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->player4_actor_id = $var;
    }

    /**
     * <code>int32 player1_scores = 10;</code>
     */
    public function getPlayer1Scores()
    {
        return $this->player1_scores;
    }

    /**
     * <code>int32 player1_scores = 10;</code>
     */
    public function setPlayer1Scores($var)
    {
        GPBUtil::checkInt32($var);
        $this->player1_scores = $var;
    }

    /**
     * <code>int32 player2_scores = 11;</code>
     */
    public function getPlayer2Scores()
    {
        return $this->player2_scores;
    }

    /**
     * <code>int32 player2_scores = 11;</code>
     */
    public function setPlayer2Scores($var)
    {
        GPBUtil::checkInt32($var);
        $this->player2_scores = $var;
    }

    /**
     * <code>int32 player3_scores = 12;</code>
     */
    public function getPlayer3Scores()
    {
        return $this->player3_scores;
    }

    /**
     * <code>int32 player3_scores = 12;</code>
     */
    public function setPlayer3Scores($var)
    {
        GPBUtil::checkInt32($var);
        $this->player3_scores = $var;
    }

    /**
     * <code>int32 player4_scores = 13;</code>
     */
    public function getPlayer4Scores()
    {
        return $this->player4_scores;
    }

    /**
     * <code>int32 player4_scores = 13;</code>
     */
    public function setPlayer4Scores($var)
    {
        GPBUtil::checkInt32($var);
        $this->player4_scores = $var;
    }

    /**
     * <code>int32 consume_card_count = 14;</code>
     */
    public function getConsumeCardCount()
    {
        return $this->consume_card_count;
    }

    /**
     * <code>int32 consume_card_count = 14;</code>
     */
    public function setConsumeCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->consume_card_count = $var;
    }

    /**
     * <code>string player1_wx_name = 15;</code>
     */
    public function getPlayer1WxName()
    {
        return $this->player1_wx_name;
    }

    /**
     * <code>string player1_wx_name = 15;</code>
     */
    public function setPlayer1WxName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player1_wx_name = $var;
    }

    /**
     * <code>string player2_wx_name = 16;</code>
     */
    public function getPlayer2WxName()
    {
        return $this->player2_wx_name;
    }

    /**
     * <code>string player2_wx_name = 16;</code>
     */
    public function setPlayer2WxName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player2_wx_name = $var;
    }

    /**
     * <code>string player3_wx_name = 17;</code>
     */
    public function getPlayer3WxName()
    {
        return $this->player3_wx_name;
    }

    /**
     * <code>string player3_wx_name = 17;</code>
     */
    public function setPlayer3WxName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player3_wx_name = $var;
    }

    /**
     * <code>string player4_wx_name = 18;</code>
     */
    public function getPlayer4WxName()
    {
        return $this->player4_wx_name;
    }

    /**
     * <code>string player4_wx_name = 18;</code>
     */
    public function setPlayer4WxName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player4_wx_name = $var;
    }

}

