<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.SendCardRecord</code>
 */
class SendCardRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 receiver_actor_id = 1;</code>
     */
    private $receiver_actor_id = 0;
    /**
     * <code>int32 card_count = 2;</code>
     */
    private $card_count = 0;
    /**
     * <code>int64 timestamp = 3;</code>
     */
    private $timestamp = 0;
    /**
     * <code>string nick_name = 4;</code>
     */
    private $nick_name = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 receiver_actor_id = 1;</code>
     */
    public function getReceiverActorId()
    {
        return $this->receiver_actor_id;
    }

    /**
     * <code>int32 receiver_actor_id = 1;</code>
     */
    public function setReceiverActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->receiver_actor_id = $var;
    }

    /**
     * <code>int32 card_count = 2;</code>
     */
    public function getCardCount()
    {
        return $this->card_count;
    }

    /**
     * <code>int32 card_count = 2;</code>
     */
    public function setCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_count = $var;
    }

    /**
     * <code>int64 timestamp = 3;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <code>int64 timestamp = 3;</code>
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;
    }

    /**
     * <code>string nick_name = 4;</code>
     */
    public function getNickName()
    {
        return $this->nick_name;
    }

    /**
     * <code>string nick_name = 4;</code>
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nick_name = $var;
    }

}

