<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_SendReceiveCard_Request</code>
 */
class B2M_SendReceiveCard_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 actor_id = 1;</code>
     */
    private $actor_id = 0;
    /**
     * <code>int32 target_actor_id = 2;</code>
     */
    private $target_actor_id = 0;
    /**
     * <code>int32 card_count = 3;</code>
     */
    private $card_count = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>int32 target_actor_id = 2;</code>
     */
    public function getTargetActorId()
    {
        return $this->target_actor_id;
    }

    /**
     * <code>int32 target_actor_id = 2;</code>
     */
    public function setTargetActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->target_actor_id = $var;
    }

    /**
     * <code>int32 card_count = 3;</code>
     */
    public function getCardCount()
    {
        return $this->card_count;
    }

    /**
     * <code>int32 card_count = 3;</code>
     */
    public function setCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_count = $var;
    }

}

