<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_Recharge_Response</code>
 */
class M2B_Recharge_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 actor_id = 1;</code>
     */
    private $actor_id = 0;
    /**
     * <code>bool success = 2;</code>
     */
    private $success = false;
    /**
     * <code>string id = 3;</code>
     */
    private $id = '';
    /**
     * <code>int32 total_card_count = 4;</code>
     */
    private $total_card_count = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>bool success = 2;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 2;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>string id = 3;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 3;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>int32 total_card_count = 4;</code>
     */
    public function getTotalCardCount()
    {
        return $this->total_card_count;
    }

    /**
     * <code>int32 total_card_count = 4;</code>
     */
    public function setTotalCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_card_count = $var;
    }

}

