<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetHistoryActiveUserCount_Response</code>
 */
class M2B_GetHistoryActiveUserCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.HistoryActiveUserCount historyActiveUserCount = 1;</code>
     */
    private $historyActiveUserCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.HistoryActiveUserCount historyActiveUserCount = 1;</code>
     */
    public function getHistoryActiveUserCount()
    {
        return $this->historyActiveUserCount;
    }

    /**
     * <code>repeated .manager.HistoryActiveUserCount historyActiveUserCount = 1;</code>
     */
    public function setHistoryActiveUserCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\HistoryActiveUserCount::class);
        $this->historyActiveUserCount = $arr;
    }

}

