<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_SendReceiveCard_Response</code>
 */
class M2B_SendReceiveCard_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 card_count = 1;</code>
     */
    private $card_count = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 card_count = 1;</code>
     */
    public function getCardCount()
    {
        return $this->card_count;
    }

    /**
     * <code>int32 card_count = 1;</code>
     */
    public function setCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_count = $var;
    }

}

