<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetTodayRechargeUserCount_Response</code>
 */
class M2B_GetTodayRechargeUserCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.TodayRechargeUserCount todayRechargeUserCount = 1;</code>
     */
    private $todayRechargeUserCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.TodayRechargeUserCount todayRechargeUserCount = 1;</code>
     */
    public function getTodayRechargeUserCount()
    {
        return $this->todayRechargeUserCount;
    }

    /**
     * <code>repeated .manager.TodayRechargeUserCount todayRechargeUserCount = 1;</code>
     */
    public function setTodayRechargeUserCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\TodayRechargeUserCount::class);
        $this->todayRechargeUserCount = $arr;
    }

}

