<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetTodayNewUserCount_Response</code>
 */
class M2B_GetTodayNewUserCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.TodayNewUserCount todayNewUserCount = 1;</code>
     */
    private $todayNewUserCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.TodayNewUserCount todayNewUserCount = 1;</code>
     */
    public function getTodayNewUserCount()
    {
        return $this->todayNewUserCount;
    }

    /**
     * <code>repeated .manager.TodayNewUserCount todayNewUserCount = 1;</code>
     */
    public function setTodayNewUserCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\TodayNewUserCount::class);
        $this->todayNewUserCount = $arr;
    }

}

