<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

namespace Head;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>head.Error_Response</code>
 */
class Error_Response extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Head::initOnce();
        parent::__construct();
    }

}

