<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

namespace Head;

/**
 * Protobuf enum <code>head.ErrorCode</code>
 */
class ErrorCode
{
    /**
     * <pre>
     * 表示没有失败
     * </pre>
     *
     * <code>ERROR_NoError = 0;</code>
     */
    const ERROR_NoError = 0;
    /**
     * <pre>
     * 未定义的错误
     * </pre>
     *
     * <code>ERROR_UndefinedError = 1;</code>
     */
    const ERROR_UndefinedError = 1;
    /**
     * <pre>
     * 传入参数错误
     * </pre>
     *
     * <code>ERROR_InputParam = 2;</code>
     */
    const ERROR_InputParam = 2;
    /**
     * <pre>
     * 创建对象失败
     * </pre>
     *
     * <code>ERROR_CreateObject = 3;</code>
     */
    const ERROR_CreateObject = 3;
    /**
     * <pre>
     * HS已注册到LS
     * </pre>
     *
     * <code>ERROR_HallServerAlreadyRegister2LoginServer = 4;</code>
     */
    const ERROR_HallServerAlreadyRegister2LoginServer = 4;
    /**
     * <pre>
     * TS已注册到HS
     * </pre>
     *
     * <code>ERROR_TableServerAlreadyRegister2HallServer = 5;</code>
     */
    const ERROR_TableServerAlreadyRegister2HallServer = 5;
    /**
     * <pre>
     * 无此账号
     * </pre>
     *
     * <code>ERROR_NoAccount = 6;</code>
     */
    const ERROR_NoAccount = 6;
    /**
     * <pre>
     * 已在其他设备登录
     * </pre>
     *
     * <code>ERROR_LoginOnOtherDevices = 7;</code>
     */
    const ERROR_LoginOnOtherDevices = 7;
    /**
     * <pre>
     * 密码错误
     * </pre>
     *
     * <code>ERROR_Password = 8;</code>
     */
    const ERROR_Password = 8;
    /**
     * <pre>
     * 插入账号表失败
     * </pre>
     *
     * <code>ERROR_InsertIntoAccountFailure = 9;</code>
     */
    const ERROR_InsertIntoAccountFailure = 9;
    /**
     * <pre>
     * 登录失败
     * </pre>
     *
     * <code>ERROR_LoginFailure = 10;</code>
     */
    const ERROR_LoginFailure = 10;
    /**
     * <pre>
     * 请求太频繁了
     * </pre>
     *
     * <code>ERROR_RequestTooFrequent = 11;</code>
     */
    const ERROR_RequestTooFrequent = 11;
    /**
     * <pre>
     * 认证已过期
     * </pre>
     *
     * <code>ERROR_AuthenticationExpired = 12;</code>
     */
    const ERROR_AuthenticationExpired = 12;
    /**
     * <pre>
     * 认证失败
     * </pre>
     *
     * <code>ERROR_AuthenticateFailure = 13;</code>
     */
    const ERROR_AuthenticateFailure = 13;
    /**
     * <pre>
     * 存储过程执行失败
     * </pre>
     *
     * <code>ERROR_DbProcedure = 14;</code>
     */
    const ERROR_DbProcedure = 14;
    /**
     * <pre>
     * 插入角色表失败
     * </pre>
     *
     * <code>ERROR_InsertIntoActorFailure = 15;</code>
     */
    const ERROR_InsertIntoActorFailure = 15;
    /**
     * <pre>
     * 已经创建了房间
     * </pre>
     *
     * <code>ERROR_AlreadyCreateRoom = 16;</code>
     */
    const ERROR_AlreadyCreateRoom = 16;
    /**
     * <pre>
     * 对象为空
     * </pre>
     *
     * <code>ERROR_ObjectIsNull = 17;</code>
     */
    const ERROR_ObjectIsNull = 17;
    /**
     * <pre>
     * 房卡不足
     * </pre>
     *
     * <code>ERROR_NotEnoughCard = 18;</code>
     */
    const ERROR_NotEnoughCard = 18;
    /**
     * <pre>
     * 系统错误
     * </pre>
     *
     * <code>ERROR_SystemError = 19;</code>
     */
    const ERROR_SystemError = 19;
    /**
     * <pre>
     * 无此角色
     * </pre>
     *
     * <code>ERROR_NoActor = 20;</code>
     */
    const ERROR_NoActor = 20;
    /**
     * <pre>
     * 无此连接
     * </pre>
     *
     * <code>ERROR_NoConnection = 21;</code>
     */
    const ERROR_NoConnection = 21;
    /**
     * <pre>
     * 房间已满
     * </pre>
     *
     * <code>ERROR_RoomsFull = 22;</code>
     */
    const ERROR_RoomsFull = 22;
    /**
     * <pre>
     * 等待创建房间中
     * </pre>
     *
     * <code>ERROR_WaitCreateRoom = 23;</code>
     */
    const ERROR_WaitCreateRoom = 23;
    /**
     * <pre>
     * 找不到大厅服务器
     * </pre>
     *
     * <code>ERROR_NoFoundHallServer = 24;</code>
     */
    const ERROR_NoFoundHallServer = 24;
    /**
     * <pre>
     * 找不到房间服务器
     * </pre>
     *
     * <code>ERROR_NoFoundTableServer = 25;</code>
     */
    const ERROR_NoFoundTableServer = 25;
    /**
     * <pre>
     * 创建房间失败
     * </pre>
     *
     * <code>ERROR_CreateRoomFailure = 26;</code>
     */
    const ERROR_CreateRoomFailure = 26;
    /**
     * <pre>
     * 分配房间ID失败
     * </pre>
     *
     * <code>ERROR_AllocRoomIdFailure = 27;</code>
     */
    const ERROR_AllocRoomIdFailure = 27;
    /**
     * <pre>
     * 添加房间失败
     * </pre>
     *
     * <code>ERROR_AddRoomFailure = 28;</code>
     */
    const ERROR_AddRoomFailure = 28;
    /**
     * <pre>
     * 没有房间可以解散
     * </pre>
     *
     * <code>ERROR_NoRoomDisband = 29;</code>
     */
    const ERROR_NoRoomDisband = 29;
    /**
     * <pre>
     * 无效角色ID
     * </pre>
     *
     * <code>ERROR_InvalidActorId = 30;</code>
     */
    const ERROR_InvalidActorId = 30;
    /**
     * <pre>
     * 不是创建者
     * </pre>
     *
     * <code>ERROR_NotCreater = 31;</code>
     */
    const ERROR_NotCreater = 31;
    /**
     * <pre>
     * 无效房间ID
     * </pre>
     *
     * <code>ERROR_InvalidRoomId = 32;</code>
     */
    const ERROR_InvalidRoomId = 32;
    /**
     * <pre>
     * 不能解散已经开始的房间
     * </pre>
     *
     * <code>ERROR_CanNotDisbandStartRoom = 33;</code>
     */
    const ERROR_CanNotDisbandStartRoom = 33;
    /**
     * <pre>
     * 已经在房间里了，不能再次加入
     * </pre>
     *
     * <code>ERROR_AlreadyInRoom = 34;</code>
     */
    const ERROR_AlreadyInRoom = 34;
    /**
     * <pre>
     * 无此房间
     * </pre>
     *
     * <code>ERROR_NotFoundRoom = 35;</code>
     */
    const ERROR_NotFoundRoom = 35;
    /**
     * <pre>
     * 当前房间已满
     * </pre>
     *
     * <code>ERROR_RoomFull = 36;</code>
     */
    const ERROR_RoomFull = 36;
    /**
     * <pre>
     * 加入房间失败
     * </pre>
     *
     * <code>ERROR_JoinRoomFailure = 37;</code>
     */
    const ERROR_JoinRoomFailure = 37;
    /**
     * <pre>
     * 已经存在此房间
     * </pre>
     *
     * <code>ERROR_AlreadyExistRoom = 38;</code>
     */
    const ERROR_AlreadyExistRoom = 38;
    /**
     * <pre>
     * 不能退出已经开始的房间
     * </pre>
     *
     * <code>ERROR_CanNotQuitStartRoom = 39;</code>
     */
    const ERROR_CanNotQuitStartRoom = 39;
    /**
     * <pre>
     * 从房间删除玩家失败
     * </pre>
     *
     * <code>ERROR_RemovePlayerFromRoom = 40;</code>
     */
    const ERROR_RemovePlayerFromRoom = 40;
    /**
     * <pre>
     * 创建玩家失败
     * </pre>
     *
     * <code>ERROR_CreatePlayerFailure = 41;</code>
     */
    const ERROR_CreatePlayerFailure = 41;
    /**
     * <pre>
     * 玩家进入房间失败
     * </pre>
     *
     * <code>ERROR_PlayerEnterRoomFailure = 42;</code>
     */
    const ERROR_PlayerEnterRoomFailure = 42;
    /**
     * <pre>
     * 已经有人发起解散
     * </pre>
     *
     * <code>ERROR_AlreadyExistSponsor = 43;</code>
     */
    const ERROR_AlreadyExistSponsor = 43;
    /**
     * <pre>
     * 房间内没有此人
     * </pre>
     *
     * <code>ERROR_NotFoundActorInRoom = 44;</code>
     */
    const ERROR_NotFoundActorInRoom = 44;
    /**
     * <pre>
     * 非法麻将
     * </pre>
     *
     * <code>ERROR_InvalidMahjong = 45;</code>
     */
    const ERROR_InvalidMahjong = 45;
    /**
     * <pre>
     * 游戏还没开始
     * </pre>
     *
     * <code>ERROR_GameNotStart = 46;</code>
     */
    const ERROR_GameNotStart = 46;
    /**
     * <pre>
     * 还没轮到你出牌
     * </pre>
     *
     * <code>ERROR_NotYourTurn = 47;</code>
     */
    const ERROR_NotYourTurn = 47;
    /**
     * <pre>
     * 找不到此麻将
     * </pre>
     *
     * <code>ERROR_NotFoundMahjong = 48;</code>
     */
    const ERROR_NotFoundMahjong = 48;
    /**
     * <pre>
     * 游戏已经开始了
     * </pre>
     *
     * <code>ERROR_GameAlreadyStart = 49;</code>
     */
    const ERROR_GameAlreadyStart = 49;
    /**
     * <pre>
     * 出牌失败
     * </pre>
     *
     * <code>ERROR_ChuPaiFailure = 50;</code>
     */
    const ERROR_ChuPaiFailure = 50;
    /**
     * <pre>
     * 杠牌失败
     * </pre>
     *
     * <code>ERROR_GangFailure = 51;</code>
     */
    const ERROR_GangFailure = 51;
    /**
     * <pre>
     * 碰牌失败
     * </pre>
     *
     * <code>ERROR_PengFailure = 52;</code>
     */
    const ERROR_PengFailure = 52;
    /**
     * <pre>
     * 吃牌失败
     * </pre>
     *
     * <code>ERROR_ChiFailure = 53;</code>
     */
    const ERROR_ChiFailure = 53;
    /**
     * <pre>
     * 胡牌失败
     * </pre>
     *
     * <code>ERROR_HuFailure = 54;</code>
     */
    const ERROR_HuFailure = 54;
    /**
     * <pre>
     * 换牌失败
     * </pre>
     *
     * <code>ERROR_ChangeMahjongFailure = 55;</code>
     */
    const ERROR_ChangeMahjongFailure = 55;
    /**
     * <pre>
     * 表决失败
     * </pre>
     *
     * <code>ERROR_VoteFailure = 56;</code>
     */
    const ERROR_VoteFailure = 56;
    /**
     * <pre>
     * 不能碰
     * </pre>
     *
     * <code>ERROR_CanNotPeng = 57;</code>
     */
    const ERROR_CanNotPeng = 57;
    /**
     * <pre>
     * 不能杠
     * </pre>
     *
     * <code>ERROR_CanNotGang = 58;</code>
     */
    const ERROR_CanNotGang = 58;
    /**
     * <pre>
     * 不能胡
     * </pre>
     *
     * <code>ERROR_CanNotHu = 59;</code>
     */
    const ERROR_CanNotHu = 59;
    /**
     * <pre>
     * 没有指定类型的杠
     * </pre>
     *
     * <code>ERROR_NoTypeGang = 60;</code>
     */
    const ERROR_NoTypeGang = 60;
    /**
     * <pre>
     * 麻将用完了
     * </pre>
     *
     * <code>ERROR_MahjongUsedUp = 61;</code>
     */
    const ERROR_MahjongUsedUp = 61;
    /**
     * <pre>
     * 等待表决完成
     * </pre>
     *
     * <code>ERROR_WaitVoteComplete = 62;</code>
     */
    const ERROR_WaitVoteComplete = 62;
    /**
     * <pre>
     * 获取下一个拿牌的人失败
     * </pre>
     *
     * <code>ERROR_GetNextMahjongTakerFailure = 63;</code>
     */
    const ERROR_GetNextMahjongTakerFailure = 63;
    /**
     * <pre>
     * 别人胡了，你不能再碰了
     * </pre>
     *
     * <code>ERROR_CanNotPengSinceOtherHu = 64;</code>
     */
    const ERROR_CanNotPengSinceOtherHu = 64;
    /**
     * <pre>
     * 别人胡了，你不能再杠了
     * </pre>
     *
     * <code>ERROR_CanNotGangSinceOtherHu = 65;</code>
     */
    const ERROR_CanNotGangSinceOtherHu = 65;
    /**
     * <pre>
     * 别人胡了，你不能拿牌了
     * </pre>
     *
     * <code>ERROR_CanNotJinSinceOtherHu = 66;</code>
     */
    const ERROR_CanNotJinSinceOtherHu = 66;
    /**
     * <pre>
     * 别人胡了，你不能出牌了
     * </pre>
     *
     * <code>ERROR_CanNotChuSinceOtherHu = 67;</code>
     */
    const ERROR_CanNotChuSinceOtherHu = 67;
    /**
     * <pre>
     * 游戏结束了
     * </pre>
     *
     * <code>ERROR_GameOver = 68;</code>
     */
    const ERROR_GameOver = 68;
    /**
     * <pre>
     * 没有一盘的结束结果
     * </pre>
     *
     * <code>ERROR_NoPlateOverResult = 69;</code>
     */
    const ERROR_NoPlateOverResult = 69;
    /**
     * <pre>
     * 没有所有盘的结束结果
     * </pre>
     *
     * <code>ERROR_NoGameOverResult = 70;</code>
     */
    const ERROR_NoGameOverResult = 70;
    /**
     * <pre>
     * 创建者不能退出房间
     * </pre>
     *
     * <code>ERROR_CreaterCanNotQuitRoom = 71;</code>
     */
    const ERROR_CreaterCanNotQuitRoom = 71;
    /**
     * <pre>
     * 插入游戏结束结果失败
     * </pre>
     *
     * <code>ERROR_InsertIntoGameOverResultFailure = 72;</code>
     */
    const ERROR_InsertIntoGameOverResultFailure = 72;
    /**
     * <pre>
     * 已经注册到监视器
     * </pre>
     *
     * <code>ERROR_GameServerAlreadyRegister2Monitor = 73;</code>
     */
    const ERROR_GameServerAlreadyRegister2Monitor = 73;
    /**
     * <pre>
     * 游戏还没有结束
     * </pre>
     *
     * <code>ERROR_GameNotOver = 74;</code>
     */
    const ERROR_GameNotOver = 74;
    /**
     * <pre>
     * 游戏还没有打完
     * </pre>
     *
     * <code>ERROR_GameNotPlayComplete = 75;</code>
     */
    const ERROR_GameNotPlayComplete = 75;
    /**
     * <pre>
     * 等待其他玩家同意解散房间
     * </pre>
     *
     * <code>ERROR_WaitOtherAgreeDisband = 76;</code>
     */
    const ERROR_WaitOtherAgreeDisband = 76;
    /**
     * <pre>
     * 没有登录验证信息
     * </pre>
     *
     * <code>ERROR_NoLoginAuthentication = 77;</code>
     */
    const ERROR_NoLoginAuthentication = 77;
    /**
     * <pre>
     * 服务器关闭中
     * </pre>
     *
     * <code>ERROR_ServerStopping = 78;</code>
     */
    const ERROR_ServerStopping = 78;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>ERROR_WxInvalidOpenId = 79;</code>
     */
    const ERROR_WxInvalidOpenId = 79;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>ERROR_WxAccountNameNotEqualOpenId = 80;</code>
     */
    const ERROR_WxAccountNameNotEqualOpenId = 80;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>ERROR_WxOpenIdNotSame = 81;</code>
     */
    const ERROR_WxOpenIdNotSame = 81;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>ERROR_WxUnionIdNotSame = 82;</code>
     */
    const ERROR_WxUnionIdNotSame = 82;
    /**
     * <pre>
     * </pre>
     *
     * <code>ERROR_LoginType = 83;</code>
     */
    const ERROR_LoginType = 83;
    /**
     * <code>ERROR_NoDbId = 84;</code>
     */
    const ERROR_NoDbId = 84;
    /**
     * <code>ERROR_InsertIntoAnnouncementFailure = 85;</code>
     */
    const ERROR_InsertIntoAnnouncementFailure = 85;
    /**
     * <code>ERROR_UpdateAnnouncementFailure = 86;</code>
     */
    const ERROR_UpdateAnnouncementFailure = 86;
    /**
     * <pre>
     * 当前后台已注册
     * </pre>
     *
     * <code>ERROR_BackendAlreadyRegister2Monitor = 87;</code>
     */
    const ERROR_BackendAlreadyRegister2Monitor = 87;
    /**
     * <pre>
     * 没有注册过账号
     * </pre>
     *
     * <code>ERROR_NotRegisterAccount = 88;</code>
     */
    const ERROR_NotRegisterAccount = 88;
    /**
     * <pre>
     * 找不到该账号
     * </pre>
     *
     * <code>ERROR_NotFoundAccount = 89;</code>
     */
    const ERROR_NotFoundAccount = 89;
    /**
     * <pre>
     * 不存在的公告
     * </pre>
     *
     * <code>ERROR_NotExistAnnouncement = 90;</code>
     */
    const ERROR_NotExistAnnouncement = 90;
    /**
     * <pre>
     * 账号被锁定
     * </pre>
     *
     * <code>ERROR_AccountLocked = 91;</code>
     */
    const ERROR_AccountLocked = 91;
    /**
     * <pre>
     * 插入赠送记录失败
     * </pre>
     *
     * <code>ERROR_InsertIntoSendRecordFailure = 92;</code>
     */
    const ERROR_InsertIntoSendRecordFailure = 92;
    /**
     * <pre>
     * 插入赠送记录失败
     * </pre>
     *
     * <code>ERROR_InsertIntoReceiveRecordFailure = 93;</code>
     */
    const ERROR_InsertIntoReceiveRecordFailure = 93;
    /**
     * <pre>
     * 插入充值记录失败
     * </pre>
     *
     * <code>ERROR_InsertIntoRechargeRecordFailure = 94;</code>
     */
    const ERROR_InsertIntoRechargeRecordFailure = 94;
    /**
     * <pre>
     * 插入房卡记录失败
     * </pre>
     *
     * <code>ERROR_InsertIntoCardRecordFailure = 95;</code>
     */
    const ERROR_InsertIntoCardRecordFailure = 95;
    /**
     * <pre>
     * 创建房间太频繁了，请稍后重试
     * </pre>
     *
     * <code>ERROR_CreateRoomTooQuick = 96;</code>
     */
    const ERROR_CreateRoomTooQuick = 96;
    /**
     * <pre>
     * 修改hs失败
     * </pre>
     *
     * <code>ERROR_UpdateHallServerFailure = 97;</code>
     */
    const ERROR_UpdateHallServerFailure = 97;
    /**
     * <pre>
     * 服务器维护中
     * </pre>
     *
     * <code>ERROR_Maintain = 98;</code>
     */
    const ERROR_Maintain = 98;
    /**
     * <pre>
     * 找不到账号服
     * </pre>
     *
     * <code>ERROR_NoFoundLoginServer = 99;</code>
     */
    const ERROR_NoFoundLoginServer = 99;
    /**
     * <pre>
     * 非微信用户禁止登录
     * </pre>
     *
     * <code>ERROR_NonWxAccountForbidLogin = 100;</code>
     */
    const ERROR_NonWxAccountForbidLogin = 100;
    /**
     * <pre>
     * 微信登录队列满
     * </pre>
     *
     * <code>ERROR_WxLoginQueueFull = 101;</code>
     */
    const ERROR_WxLoginQueueFull = 101;
    /**
     * <pre>
     * 超时最大创建房间数
     * </pre>
     *
     * <code>ERROR_ExtendMaxCreateRoomCount = 102;</code>
     */
    const ERROR_ExtendMaxCreateRoomCount = 102;
    /**
     * <pre>
     * 角色不在线
     * </pre>
     *
     * <code>ERROR_ActorOffline = 103;</code>
     */
    const ERROR_ActorOffline = 103;
}

