<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

namespace Head;

/**
 * Protobuf enum <code>head.Modules</code>
 */
class Modules
{
    /**
     * <code>HEAD = 0;</code>
     */
    const HEAD = 0;
    /**
     * <code>MANAGER = 2000;</code>
     */
    const MANAGER = 2000;
}

