<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_RechargeResult_Request</code>
 */
class B2M_RechargeResult_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>int32 actor_id = 2;</code>
     */
    private $actor_id = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>int32 actor_id = 2;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 2;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

}

