<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

namespace Head;

/**
 * <pre>
 * 游戏类型
 * </pre>
 *
 * Protobuf enum <code>head.GameId</code>
 */
class GameId
{
    /**
     * <code>NoUse = 0;</code>
     */
    const NoUse = 0;
    /**
     * <pre>
     * 江西-宜黄
     * </pre>
     *
     * <code>JiangXi_YiHuang = 1;</code>
     */
    const JiangXi_YiHuang = 1;
}

