<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetLiuCun_Response</code>
 */
class M2B_GetLiuCun_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.LiuCun liuCun = 1;</code>
     */
    private $liuCun;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.LiuCun liuCun = 1;</code>
     */
    public function getLiuCun()
    {
        return $this->liuCun;
    }

    /**
     * <code>repeated .manager.LiuCun liuCun = 1;</code>
     */
    public function setLiuCun(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\LiuCun::class);
        $this->liuCun = $arr;
    }

}

