<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_RemoveAnnouncement_Request</code>
 */
class B2M_RemoveAnnouncement_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 time = 1;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 time = 1;</code>
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * <code>int64 time = 1;</code>
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;
    }

}

