<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 充值
 * </pre>
 *
 * Protobuf type <code>manager.B2M_Recharge_Request</code>
 */
class B2M_Recharge_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 actor_id = 1;</code>
     */
    private $actor_id = 0;
    /**
     * <code>int32 add_card_count = 2;</code>
     */
    private $add_card_count = 0;
    /**
     * <code>int32 operator_id = 3;</code>
     */
    private $operator_id = 0;
    /**
     * <code>int32 money = 4;</code>
     */
    private $money = 0;
    /**
     * <pre>
     * 渠道
     * </pre>
     *
     * <code>int32 channel = 5;</code>
     */
    private $channel = 0;
    /**
     * <pre>
     * 商品ID
     * </pre>
     *
     * <code>int32 item = 6;</code>
     */
    private $item = 0;
    /**
     * <pre>
     * 充值订单号
     * </pre>
     *
     * <code>string id = 7;</code>
     */
    private $id = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>int32 add_card_count = 2;</code>
     */
    public function getAddCardCount()
    {
        return $this->add_card_count;
    }

    /**
     * <code>int32 add_card_count = 2;</code>
     */
    public function setAddCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->add_card_count = $var;
    }

    /**
     * <code>int32 operator_id = 3;</code>
     */
    public function getOperatorId()
    {
        return $this->operator_id;
    }

    /**
     * <code>int32 operator_id = 3;</code>
     */
    public function setOperatorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->operator_id = $var;
    }

    /**
     * <code>int32 money = 4;</code>
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * <code>int32 money = 4;</code>
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->money = $var;
    }

    /**
     * <pre>
     * 渠道
     * </pre>
     *
     * <code>int32 channel = 5;</code>
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * <pre>
     * 渠道
     * </pre>
     *
     * <code>int32 channel = 5;</code>
     */
    public function setChannel($var)
    {
        GPBUtil::checkInt32($var);
        $this->channel = $var;
    }

    /**
     * <pre>
     * 商品ID
     * </pre>
     *
     * <code>int32 item = 6;</code>
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * <pre>
     * 商品ID
     * </pre>
     *
     * <code>int32 item = 6;</code>
     */
    public function setItem($var)
    {
        GPBUtil::checkInt32($var);
        $this->item = $var;
    }

    /**
     * <pre>
     * 充值订单号
     * </pre>
     *
     * <code>string id = 7;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <pre>
     * 充值订单号
     * </pre>
     *
     * <code>string id = 7;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

}

