<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_GetHistoryActiveUserCount_Request</code>
 */
class B2M_GetHistoryActiveUserCount_Request extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

}

