<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_FindRegisterAccount_Request</code>
 */
class B2M_FindRegisterAccount_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string union_id = 1;</code>
     */
    private $union_id = '';
    /**
     * <code>string open_id = 2;</code>
     */
    private $open_id = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>string union_id = 1;</code>
     */
    public function getUnionId()
    {
        return $this->union_id;
    }

    /**
     * <code>string union_id = 1;</code>
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_id = $var;
    }

    /**
     * <code>string open_id = 2;</code>
     */
    public function getOpenId()
    {
        return $this->open_id;
    }

    /**
     * <code>string open_id = 2;</code>
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_id = $var;
    }

}

