<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_SearchAccount_Request</code>
 */
class B2M_SearchAccount_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string wx_union_id = 1;</code>
     */
    private $wx_union_id = '';
    /**
     * <code>string wx_open_id = 2;</code>
     */
    private $wx_open_id = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>string wx_union_id = 1;</code>
     */
    public function getWxUnionId()
    {
        return $this->wx_union_id;
    }

    /**
     * <code>string wx_union_id = 1;</code>
     */
    public function setWxUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wx_union_id = $var;
    }

    /**
     * <code>string wx_open_id = 2;</code>
     */
    public function getWxOpenId()
    {
        return $this->wx_open_id;
    }

    /**
     * <code>string wx_open_id = 2;</code>
     */
    public function setWxOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wx_open_id = $var;
    }

}

