<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

/**
 * <pre>
 * 消息号
 * </pre>
 *
 * Protobuf enum <code>manager.Cmd</code>
 */
class Cmd
{
    /**
     * <code>CMD_NoUse = 0;</code>
     */
    const CMD_NoUse = 0;
    /**
     * <pre>
     * 注册后台
     * </pre>
     *
     * <code>CMD_B2M_Register_Request = 2001;</code>
     */
    const CMD_B2M_Register_Request = 2001;
    /**
     * <code>CMD_M2B_Register_Response = 2002;</code>
     */
    const CMD_M2B_Register_Response = 2002;
    /**
     * <pre>
     * 充值
     * </pre>
     *
     * <code>CMD_B2M_Recharge_Request = 2003;</code>
     */
    const CMD_B2M_Recharge_Request = 2003;
    /**
     * <code>CMD_M2B_Recharge_Response = 2004;</code>
     */
    const CMD_M2B_Recharge_Response = 2004;
    /**
     * <pre>
     * 查找角色信息
     * </pre>
     *
     * <code>CMD_B2M_SearchActor_Request = 2005;</code>
     */
    const CMD_B2M_SearchActor_Request = 2005;
    /**
     * <code>CMD_M2B_SearchActor_Response = 2006;</code>
     */
    const CMD_M2B_SearchActor_Response = 2006;
    /**
     * <pre>
     * 查找账号信息
     * </pre>
     *
     * <code>CMD_B2M_SearchAccount_Request = 2007;</code>
     */
    const CMD_B2M_SearchAccount_Request = 2007;
    /**
     * <code>CMD_M2B_SearchAccount_Response = 2008;</code>
     */
    const CMD_M2B_SearchAccount_Response = 2008;
    /**
     * <pre>
     * 查找服务器信息
     * </pre>
     *
     * <code>CMD_B2M_GetServerInfo_Request = 2009;</code>
     */
    const CMD_B2M_GetServerInfo_Request = 2009;
    /**
     * <code>CMD_M2B_GetServerInfo_Response = 2010;</code>
     */
    const CMD_M2B_GetServerInfo_Response = 2010;
    /**
     * <pre>
     * 查找账号有没有注册过
     * </pre>
     *
     * <code>CMD_B2M_FindRegisterAccount_Request = 2011;</code>
     */
    const CMD_B2M_FindRegisterAccount_Request = 2011;
    /**
     * <code>CMD_M2B_FindRegisterAccount_Response = 2012;</code>
     */
    const CMD_M2B_FindRegisterAccount_Response = 2012;
    /**
     * <pre>
     * 注册为代码
     * </pre>
     *
     * <code>CMD_B2M_RegisterAgent_Request = 2013;</code>
     */
    const CMD_B2M_RegisterAgent_Request = 2013;
    /**
     * <code>CMD_M2B_RegisterAgent_Response = 2014;</code>
     */
    const CMD_M2B_RegisterAgent_Response = 2014;
    /**
     * <pre>
     * 获得当前滚动公告栏信息
     * </pre>
     *
     * <code>CMD_B2M_GetRollingBulletin_Request = 2015;</code>
     */
    const CMD_B2M_GetRollingBulletin_Request = 2015;
    /**
     * <code>CMD_M2B_GetRollingBulletin_Response = 2016;</code>
     */
    const CMD_M2B_GetRollingBulletin_Response = 2016;
    /**
     * <pre>
     * 设置当前滚动公告栏信息
     * </pre>
     *
     * <code>CMD_B2M_SetRollingBulletin_Request = 2017;</code>
     */
    const CMD_B2M_SetRollingBulletin_Request = 2017;
    /**
     * <code>CMD_M2B_SetRollingBulletin_Response = 2018;</code>
     */
    const CMD_M2B_SetRollingBulletin_Response = 2018;
    /**
     * <pre>
     * 获得当前公告信息
     * </pre>
     *
     * <code>CMD_B2M_GetAnnouncement_Request = 2019;</code>
     */
    const CMD_B2M_GetAnnouncement_Request = 2019;
    /**
     * <code>CMD_M2B_GetAnnouncement_Response = 2020;</code>
     */
    const CMD_M2B_GetAnnouncement_Response = 2020;
    /**
     * <pre>
     * 修改当前公告信息，一次只能修改一条
     * </pre>
     *
     * <code>CMD_B2M_ModifyAnnouncement_Request = 2021;</code>
     */
    const CMD_B2M_ModifyAnnouncement_Request = 2021;
    /**
     * <code>CMD_M2B_ModifyAnnouncement_Response = 2022;</code>
     */
    const CMD_M2B_ModifyAnnouncement_Response = 2022;
    /**
     * <pre>
     * 添加新公告信息，一次只能添加一条
     * </pre>
     *
     * <code>CMD_B2M_AddNewAnnouncement_Request = 2023;</code>
     */
    const CMD_B2M_AddNewAnnouncement_Request = 2023;
    /**
     * <code>CMD_M2B_AddNewAnnouncement_Response = 2024;</code>
     */
    const CMD_M2B_AddNewAnnouncement_Response = 2024;
    /**
     * <pre>
     * 赠送房卡
     * </pre>
     *
     * <code>CMD_B2M_SendReceiveCard_Request = 2025;</code>
     */
    const CMD_B2M_SendReceiveCard_Request = 2025;
    /**
     * <code>CMD_M2B_SendReceiveCard_Response = 2026;</code>
     */
    const CMD_M2B_SendReceiveCard_Response = 2026;
    /**
     * <pre>
     * 获取发送房间记录
     * </pre>
     *
     * <code>CMD_B2M_RetriveSendCardRecord_Request = 2027;</code>
     */
    const CMD_B2M_RetriveSendCardRecord_Request = 2027;
    /**
     * <code>CMD_M2B_RetriveSendCardRecord_Response = 2028;</code>
     */
    const CMD_M2B_RetriveSendCardRecord_Response = 2028;
    /**
     * <pre>
     * 获取接收房间记录
     * </pre>
     *
     * <code>CMD_B2M_RetriveReceiveCardRecord_Request = 2029;</code>
     */
    const CMD_B2M_RetriveReceiveCardRecord_Request = 2029;
    /**
     * <code>CMD_M2B_RetriveReceiveCardRecord_Response = 2030;</code>
     */
    const CMD_M2B_RetriveReceiveCardRecord_Response = 2030;
    /**
     * <pre>
     * 获取今日充值排行
     * </pre>
     *
     * <code>CMD_B2M_TodayRecharge_Request = 2031;</code>
     */
    const CMD_B2M_TodayRecharge_Request = 2031;
    /**
     * <code>CMD_M2B_TodayRecharge_Response = 2032;</code>
     */
    const CMD_M2B_TodayRecharge_Response = 2032;
    /**
     * <pre>
     * 获取本月充值排行
     * </pre>
     *
     * <code>CMD_B2M_MonthRecharge_Request = 2033;</code>
     */
    const CMD_B2M_MonthRecharge_Request = 2033;
    /**
     * <code>CMD_M2B_MonthRecharge_Response = 2034;</code>
     */
    const CMD_M2B_MonthRecharge_Response = 2034;
    /**
     * <pre>
     * 获取上个月充值排行
     * </pre>
     *
     * <code>CMD_B2M_MonthPre1Recharge_Request = 2035;</code>
     */
    const CMD_B2M_MonthPre1Recharge_Request = 2035;
    /**
     * <code>CMD_M2B_MonthPre1Recharge_Response = 2036;</code>
     */
    const CMD_M2B_MonthPre1Recharge_Response = 2036;
    /**
     * <pre>
     * 获取累计充值排行
     * </pre>
     *
     * <code>CMD_B2M_AllRecharge_Request = 2037;</code>
     */
    const CMD_B2M_AllRecharge_Request = 2037;
    /**
     * <code>CMD_M2B_AllRecharge_Response = 2038;</code>
     */
    const CMD_M2B_AllRecharge_Response = 2038;
    /**
     * <pre>
     * 获取注册代理列表
     * </pre>
     *
     * <code>CMD_B2M_GetRegisterAgent_Request = 2039;</code>
     */
    const CMD_B2M_GetRegisterAgent_Request = 2039;
    /**
     * <code>CMD_M2B_GetRegisterAgent_Response = 2040;</code>
     */
    const CMD_M2B_GetRegisterAgent_Response = 2040;
    /**
     * <pre>
     * 通过代理注册
     * </pre>
     *
     * <code>CMD_B2M_ConfirmAgentRegister_Request = 2041;</code>
     */
    const CMD_B2M_ConfirmAgentRegister_Request = 2041;
    /**
     * <code>CMD_M2B_ConfirmAgentRegister_Response = 2042;</code>
     */
    const CMD_M2B_ConfirmAgentRegister_Response = 2042;
    /**
     * <pre>
     * 获取注册代理列表大小
     * </pre>
     *
     * <code>CMD_B2M_GetRegisterAgentSize_Request = 2043;</code>
     */
    const CMD_B2M_GetRegisterAgentSize_Request = 2043;
    /**
     * <code>CMD_M2B_GetRegisterAgentSize_Response = 2044;</code>
     */
    const CMD_M2B_GetRegisterAgentSize_Response = 2044;
    /**
     * <pre>
     * 今天活跃用户数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayActiveUserCount_Request = 2045;</code>
     */
    const CMD_B2M_GetTodayActiveUserCount_Request = 2045;
    /**
     * <code>CMD_M2B_GetTodayActiveUserCount_Response = 2046;</code>
     */
    const CMD_M2B_GetTodayActiveUserCount_Response = 2046;
    /**
     * <pre>
     * 今天充值卡数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayRechargeCardCount_Request = 2047;</code>
     */
    const CMD_B2M_GetTodayRechargeCardCount_Request = 2047;
    /**
     * <code>CMD_M2B_GetTodayRechargeCardCount_Response = 2048;</code>
     */
    const CMD_M2B_GetTodayRechargeCardCount_Response = 2048;
    /**
     * <pre>
     * 今天充值金额数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayRechargeMoney_Request = 2049;</code>
     */
    const CMD_B2M_GetTodayRechargeMoney_Request = 2049;
    /**
     * <code>CMD_M2B_GetTodayRechargeMoney_Response = 2050;</code>
     */
    const CMD_M2B_GetTodayRechargeMoney_Response = 2050;
    /**
     * <pre>
     * 今天充值用户数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayRechargeUserCount_Request = 2051;</code>
     */
    const CMD_B2M_GetTodayRechargeUserCount_Request = 2051;
    /**
     * <code>CMD_M2B_GetTodayRechargeUserCount_Response = 2052;</code>
     */
    const CMD_M2B_GetTodayRechargeUserCount_Response = 2052;
    /**
     * <pre>
     * 今天房间数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayRoomCount_Request = 2053;</code>
     */
    const CMD_B2M_GetTodayRoomCount_Request = 2053;
    /**
     * <code>CMD_M2B_GetTodayRoomCount_Response = 2054;</code>
     */
    const CMD_M2B_GetTodayRoomCount_Response = 2054;
    /**
     * <pre>
     * 留存
     * </pre>
     *
     * <code>CMD_B2M_GetLiuCun_Request = 2055;</code>
     */
    const CMD_B2M_GetLiuCun_Request = 2055;
    /**
     * <code>CMD_M2B_GetLiuCun_Response = 2056;</code>
     */
    const CMD_M2B_GetLiuCun_Response = 2056;
    /**
     * <pre>
     * 历史活跃用户数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryActiveUserCount_Request = 2057;</code>
     */
    const CMD_B2M_GetHistoryActiveUserCount_Request = 2057;
    /**
     * <code>CMD_M2B_GetHistoryActiveUserCount_Response = 2058;</code>
     */
    const CMD_M2B_GetHistoryActiveUserCount_Response = 2058;
    /**
     * <pre>
     * 历史充值卡数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryRechargeCardCount_Request = 2059;</code>
     */
    const CMD_B2M_GetHistoryRechargeCardCount_Request = 2059;
    /**
     * <code>CMD_M2B_GetHistoryRechargeCardCount_Response = 2060;</code>
     */
    const CMD_M2B_GetHistoryRechargeCardCount_Response = 2060;
    /**
     * <pre>
     * 历史充值金额数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryRechargeMoney_Request = 2061;</code>
     */
    const CMD_B2M_GetHistoryRechargeMoney_Request = 2061;
    /**
     * <code>CMD_M2B_GetHistoryRechargeMoney_Response = 2062;</code>
     */
    const CMD_M2B_GetHistoryRechargeMoney_Response = 2062;
    /**
     * <pre>
     * 历史充值用户数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryRechargeUserCount_Request = 2063;</code>
     */
    const CMD_B2M_GetHistoryRechargeUserCount_Request = 2063;
    /**
     * <code>CMD_M2B_GetHistoryRechargeUserCount_Response = 2064;</code>
     */
    const CMD_M2B_GetHistoryRechargeUserCount_Response = 2064;
    /**
     * <pre>
     * 历史房间数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryRoomCount_Request = 2065;</code>
     */
    const CMD_B2M_GetHistoryRoomCount_Request = 2065;
    /**
     * <code>CMD_M2B_GetHistoryRoomCount_Response = 2066;</code>
     */
    const CMD_M2B_GetHistoryRoomCount_Response = 2066;
    /**
     * <pre>
     * 今天新增用户数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayNewUserCount_Request = 2067;</code>
     */
    const CMD_B2M_GetTodayNewUserCount_Request = 2067;
    /**
     * <code>CMD_M2B_GetTodayNewUserCount_Response = 2068;</code>
     */
    const CMD_M2B_GetTodayNewUserCount_Response = 2068;
    /**
     * <pre>
     * 历史新增用户数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryNewUserCount_Request = 2069;</code>
     */
    const CMD_B2M_GetHistoryNewUserCount_Request = 2069;
    /**
     * <code>CMD_M2B_GetHistoryNewUserCount_Response = 2070;</code>
     */
    const CMD_M2B_GetHistoryNewUserCount_Response = 2070;
    /**
     * <pre>
     * 今天消耗房卡数
     * </pre>
     *
     * <code>CMD_B2M_GetTodayConsumeCardCount_Request = 2071;</code>
     */
    const CMD_B2M_GetTodayConsumeCardCount_Request = 2071;
    /**
     * <code>CMD_M2B_GetTodayConsumeCardCount_Response = 2072;</code>
     */
    const CMD_M2B_GetTodayConsumeCardCount_Response = 2072;
    /**
     * <pre>
     * 历史消耗房卡数
     * </pre>
     *
     * <code>CMD_B2M_GetHistoryConsumeCardCount_Request = 2073;</code>
     */
    const CMD_B2M_GetHistoryConsumeCardCount_Request = 2073;
    /**
     * <code>CMD_M2B_GetHistoryConsumeCardCount_Response = 2074;</code>
     */
    const CMD_M2B_GetHistoryConsumeCardCount_Response = 2074;
    /**
     * <pre>
     * 商品列表
     * </pre>
     *
     * <code>CMD_B2M_GetMallItems_Request = 2075;</code>
     */
    const CMD_B2M_GetMallItems_Request = 2075;
    /**
     * <code>CMD_M2B_GetMallItems_Response = 2076;</code>
     */
    const CMD_M2B_GetMallItems_Response = 2076;
    /**
     * <pre>
     * 请求充值订单号
     * </pre>
     *
     * <code>CMD_B2M_RequestRechargeId_Request = 2077;</code>
     */
    const CMD_B2M_RequestRechargeId_Request = 2077;
    /**
     * <code>CMD_M2B_RequestRechargeId_Response = 2078;</code>
     */
    const CMD_M2B_RequestRechargeId_Response = 2078;
    /**
     * <pre>
     * 获得代理统计数
     * </pre>
     *
     * <code>CMD_B2M_GetAgentCount_Request = 2079;</code>
     */
    const CMD_B2M_GetAgentCount_Request = 2079;
    /**
     * <code>CMD_M2B_GetAgentCount_Response = 2080;</code>
     */
    const CMD_M2B_GetAgentCount_Response = 2080;
    /**
     * <pre>
     * 删除公告信息
     * </pre>
     *
     * <code>CMD_B2M_RemoveAnnouncement_Request = 2081;</code>
     */
    const CMD_B2M_RemoveAnnouncement_Request = 2081;
    /**
     * <code>CMD_M2B_RemoveAnnouncement_Response = 2082;</code>
     */
    const CMD_M2B_RemoveAnnouncement_Response = 2082;
    /**
     * <pre>
     * 获得最近开房
     * </pre>
     *
     * <code>CMD_B2M_GetRecentCreateRoom_Request = 2083;</code>
     */
    const CMD_B2M_GetRecentCreateRoom_Request = 2083;
    /**
     * <code>CMD_M2B_GetRecentCreateRoom_Response = 2084;</code>
     */
    const CMD_M2B_GetRecentCreateRoom_Response = 2084;
}

