<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetHistoryConsumeCardCount_Response</code>
 */
class M2B_GetHistoryConsumeCardCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.HistoryConsumeCardCount historyConsumeCardCount = 1;</code>
     */
    private $historyConsumeCardCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.HistoryConsumeCardCount historyConsumeCardCount = 1;</code>
     */
    public function getHistoryConsumeCardCount()
    {
        return $this->historyConsumeCardCount;
    }

    /**
     * <code>repeated .manager.HistoryConsumeCardCount historyConsumeCardCount = 1;</code>
     */
    public function setHistoryConsumeCardCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\HistoryConsumeCardCount::class);
        $this->historyConsumeCardCount = $arr;
    }

}

