<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_SearchAccount_Response</code>
 */
class M2B_SearchAccount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string real_name = 1;</code>
     */
    private $real_name = '';
    /**
     * <code>int32 promotion_code = 2;</code>
     */
    private $promotion_code = 0;
    /**
     * <code>int32 card_count = 3;</code>
     */
    private $card_count = 0;
    /**
     * <code>int32 actor_id = 4;</code>
     */
    private $actor_id = 0;
    /**
     * <code>int32 introducer = 5;</code>
     */
    private $introducer = 0;
    /**
     * <code>string telephone = 6;</code>
     */
    private $telephone = '';
    /**
     * <pre>
     * 0未注册代理 1已注册代理 2已通过代理审核
     * </pre>
     *
     * <code>int32 agent = 7;</code>
     */
    private $agent = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>string real_name = 1;</code>
     */
    public function getRealName()
    {
        return $this->real_name;
    }

    /**
     * <code>string real_name = 1;</code>
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, True);
        $this->real_name = $var;
    }

    /**
     * <code>int32 promotion_code = 2;</code>
     */
    public function getPromotionCode()
    {
        return $this->promotion_code;
    }

    /**
     * <code>int32 promotion_code = 2;</code>
     */
    public function setPromotionCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->promotion_code = $var;
    }

    /**
     * <code>int32 card_count = 3;</code>
     */
    public function getCardCount()
    {
        return $this->card_count;
    }

    /**
     * <code>int32 card_count = 3;</code>
     */
    public function setCardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_count = $var;
    }

    /**
     * <code>int32 actor_id = 4;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 4;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>int32 introducer = 5;</code>
     */
    public function getIntroducer()
    {
        return $this->introducer;
    }

    /**
     * <code>int32 introducer = 5;</code>
     */
    public function setIntroducer($var)
    {
        GPBUtil::checkInt32($var);
        $this->introducer = $var;
    }

    /**
     * <code>string telephone = 6;</code>
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * <code>string telephone = 6;</code>
     */
    public function setTelephone($var)
    {
        GPBUtil::checkString($var, True);
        $this->telephone = $var;
    }

    /**
     * <pre>
     * 0未注册代理 1已注册代理 2已通过代理审核
     * </pre>
     *
     * <code>int32 agent = 7;</code>
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     * <pre>
     * 0未注册代理 1已注册代理 2已通过代理审核
     * </pre>
     *
     * <code>int32 agent = 7;</code>
     */
    public function setAgent($var)
    {
        GPBUtil::checkInt32($var);
        $this->agent = $var;
    }

}

