<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetRollingBulletin_Response</code>
 */
class M2B_GetRollingBulletin_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string text = 1;</code>
     */
    private $text = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>string text = 1;</code>
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * <code>string text = 1;</code>
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;
    }

}

