<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetHistoryRoomCount_Response</code>
 */
class M2B_GetHistoryRoomCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.HistoryRoomCount historyRoomCount = 1;</code>
     */
    private $historyRoomCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.HistoryRoomCount historyRoomCount = 1;</code>
     */
    public function getHistoryRoomCount()
    {
        return $this->historyRoomCount;
    }

    /**
     * <code>repeated .manager.HistoryRoomCount historyRoomCount = 1;</code>
     */
    public function setHistoryRoomCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\HistoryRoomCount::class);
        $this->historyRoomCount = $arr;
    }

}

