<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetAgentCount_Response</code>
 */
class M2B_GetAgentCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 actor_id = 1;</code>
     */
    private $actor_id = 0;
    /**
     * <code>int32 actor_count_d1 = 2;</code>
     */
    private $actor_count_d1 = 0;
    /**
     * <code>int32 actor_count_d2 = 3;</code>
     */
    private $actor_count_d2 = 0;
    /**
     * <code>int32 actor_count_d7 = 4;</code>
     */
    private $actor_count_d7 = 0;
    /**
     * <code>int32 actor_count_all = 5;</code>
     */
    private $actor_count_all = 0;
    /**
     * <code>int32 send_card_count_d1 = 6;</code>
     */
    private $send_card_count_d1 = 0;
    /**
     * <code>int32 send_card_count_d2 = 7;</code>
     */
    private $send_card_count_d2 = 0;
    /**
     * <code>int32 send_card_count_d7 = 8;</code>
     */
    private $send_card_count_d7 = 0;
    /**
     * <code>int32 send_card_count_all = 9;</code>
     */
    private $send_card_count_all = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * <code>int32 actor_id = 1;</code>
     */
    public function setActorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_id = $var;
    }

    /**
     * <code>int32 actor_count_d1 = 2;</code>
     */
    public function getActorCountD1()
    {
        return $this->actor_count_d1;
    }

    /**
     * <code>int32 actor_count_d1 = 2;</code>
     */
    public function setActorCountD1($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_count_d1 = $var;
    }

    /**
     * <code>int32 actor_count_d2 = 3;</code>
     */
    public function getActorCountD2()
    {
        return $this->actor_count_d2;
    }

    /**
     * <code>int32 actor_count_d2 = 3;</code>
     */
    public function setActorCountD2($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_count_d2 = $var;
    }

    /**
     * <code>int32 actor_count_d7 = 4;</code>
     */
    public function getActorCountD7()
    {
        return $this->actor_count_d7;
    }

    /**
     * <code>int32 actor_count_d7 = 4;</code>
     */
    public function setActorCountD7($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_count_d7 = $var;
    }

    /**
     * <code>int32 actor_count_all = 5;</code>
     */
    public function getActorCountAll()
    {
        return $this->actor_count_all;
    }

    /**
     * <code>int32 actor_count_all = 5;</code>
     */
    public function setActorCountAll($var)
    {
        GPBUtil::checkInt32($var);
        $this->actor_count_all = $var;
    }

    /**
     * <code>int32 send_card_count_d1 = 6;</code>
     */
    public function getSendCardCountD1()
    {
        return $this->send_card_count_d1;
    }

    /**
     * <code>int32 send_card_count_d1 = 6;</code>
     */
    public function setSendCardCountD1($var)
    {
        GPBUtil::checkInt32($var);
        $this->send_card_count_d1 = $var;
    }

    /**
     * <code>int32 send_card_count_d2 = 7;</code>
     */
    public function getSendCardCountD2()
    {
        return $this->send_card_count_d2;
    }

    /**
     * <code>int32 send_card_count_d2 = 7;</code>
     */
    public function setSendCardCountD2($var)
    {
        GPBUtil::checkInt32($var);
        $this->send_card_count_d2 = $var;
    }

    /**
     * <code>int32 send_card_count_d7 = 8;</code>
     */
    public function getSendCardCountD7()
    {
        return $this->send_card_count_d7;
    }

    /**
     * <code>int32 send_card_count_d7 = 8;</code>
     */
    public function setSendCardCountD7($var)
    {
        GPBUtil::checkInt32($var);
        $this->send_card_count_d7 = $var;
    }

    /**
     * <code>int32 send_card_count_all = 9;</code>
     */
    public function getSendCardCountAll()
    {
        return $this->send_card_count_all;
    }

    /**
     * <code>int32 send_card_count_all = 9;</code>
     */
    public function setSendCardCountAll($var)
    {
        GPBUtil::checkInt32($var);
        $this->send_card_count_all = $var;
    }

}

