<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetServerInfo_Response</code>
 */
class M2B_GetServerInfo_Response extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

}

