<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetHistoryRechargeMoney_Response</code>
 */
class M2B_GetHistoryRechargeMoney_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.HistoryRechargeMoney historyRechargeMoney = 1;</code>
     */
    private $historyRechargeMoney;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.HistoryRechargeMoney historyRechargeMoney = 1;</code>
     */
    public function getHistoryRechargeMoney()
    {
        return $this->historyRechargeMoney;
    }

    /**
     * <code>repeated .manager.HistoryRechargeMoney historyRechargeMoney = 1;</code>
     */
    public function setHistoryRechargeMoney(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\HistoryRechargeMoney::class);
        $this->historyRechargeMoney = $arr;
    }

}

