<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetHistoryRechargeUserCount_Response</code>
 */
class M2B_GetHistoryRechargeUserCount_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.HistoryRechargeUserCount historyRechargeUserCount = 1;</code>
     */
    private $historyRechargeUserCount;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.HistoryRechargeUserCount historyRechargeUserCount = 1;</code>
     */
    public function getHistoryRechargeUserCount()
    {
        return $this->historyRechargeUserCount;
    }

    /**
     * <code>repeated .manager.HistoryRechargeUserCount historyRechargeUserCount = 1;</code>
     */
    public function setHistoryRechargeUserCount(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\HistoryRechargeUserCount::class);
        $this->historyRechargeUserCount = $arr;
    }

}

