<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetMallItems_Response</code>
 */
class M2B_GetMallItems_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.MallItem mallItem = 1;</code>
     */
    private $mallItem;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.MallItem mallItem = 1;</code>
     */
    public function getMallItem()
    {
        return $this->mallItem;
    }

    /**
     * <code>repeated .manager.MallItem mallItem = 1;</code>
     */
    public function setMallItem(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\MallItem::class);
        $this->mallItem = $arr;
    }

}

