<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.TodayActiveUserCount</code>
 */
class TodayActiveUserCount extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 index = 1;</code>
     */
    private $index = 0;
    /**
     * <code>int32 count = 2;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 index = 1;</code>
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * <code>int32 index = 1;</code>
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;
    }

    /**
     * <code>int32 count = 2;</code>
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * <code>int32 count = 2;</code>
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;
    }

}

