<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.B2M_RegisterAgent_Request</code>
 */
class B2M_RegisterAgent_Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string union_id = 1;</code>
     */
    private $union_id = '';
    /**
     * <code>string open_id = 2;</code>
     */
    private $open_id = '';
    /**
     * <code>string phone = 3;</code>
     */
    private $phone = '';
    /**
     * <code>string name = 4;</code>
     */
    private $name = '';
    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string wxId = 5;</code>
     */
    private $wxId = '';

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>string union_id = 1;</code>
     */
    public function getUnionId()
    {
        return $this->union_id;
    }

    /**
     * <code>string union_id = 1;</code>
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_id = $var;
    }

    /**
     * <code>string open_id = 2;</code>
     */
    public function getOpenId()
    {
        return $this->open_id;
    }

    /**
     * <code>string open_id = 2;</code>
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_id = $var;
    }

    /**
     * <code>string phone = 3;</code>
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * <code>string phone = 3;</code>
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;
    }

    /**
     * <code>string name = 4;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 4;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string wxId = 5;</code>
     */
    public function getWxId()
    {
        return $this->wxId;
    }

    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string wxId = 5;</code>
     */
    public function setWxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxId = $var;
    }

}

