<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>manager.M2B_GetRegisterAgent_Response</code>
 */
class M2B_GetRegisterAgent_Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .manager.RegisterAgent register_agent = 1;</code>
     */
    private $register_agent;
    /**
     * <pre>
     * 总共多少行数
     * </pre>
     *
     * <code>int32 size = 2;</code>
     */
    private $size = 0;
    /**
     * <pre>
     * 一页多少行数
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     */
    private $page_size = 0;

    public function __construct() {
        \GPBMetadata\Manager::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .manager.RegisterAgent register_agent = 1;</code>
     */
    public function getRegisterAgent()
    {
        return $this->register_agent;
    }

    /**
     * <code>repeated .manager.RegisterAgent register_agent = 1;</code>
     */
    public function setRegisterAgent(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Manager\RegisterAgent::class);
        $this->register_agent = $arr;
    }

    /**
     * <pre>
     * 总共多少行数
     * </pre>
     *
     * <code>int32 size = 2;</code>
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * <pre>
     * 总共多少行数
     * </pre>
     *
     * <code>int32 size = 2;</code>
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;
    }

    /**
     * <pre>
     * 一页多少行数
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * <pre>
     * 一页多少行数
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;
    }

}

